name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build

      - uses: actions/checkout@v4
      - name: Commit dist folder
      - run: git add .dist
      - run: git commit -a -m 'Github Action. Build and deploy'
      - run: git push
     
